# This is the config file for the python project GDBMiner
# Copyright (c) 2023 Robert Bosch GmbH
# SPDX-License-Identifier: AGPL-3.0
[metadata]
name = GDBMiner
version = 0.0.1
description = Debugger-driven Grammar Mining
author = Max Eisele
author_email = MaxCamillo.Eisele@bosch.com
url = https://link-to-your-project

[options]
packages = find:
package_dir =  
    =src
zip_safe = True
include_package_data = True
