# Here are basic configurations which concern the generation of the grammar in general.
[BASIC]
seed_directory = "./example_firmware/stm32_arduinojson/seeds"

# Path to a directory where output files (e.g. graphs, logfiles) are stored.
output_directory = "./output/stm32_arduinojson/"

binary_file = "./example_firmware/stm32_arduinojson/.pio/build/disco_l4s5i_iot01a/firmware.elf"

eval_directory = "./example_firmware/stm32_arduinojson/eval"


# This section contains configurations for the communication with the board on which the SuT is running.
[Connection]
input_channel = "serial"
port = "/dev/ttyACM0"
baud_rate = 9600

# This section contains configurations which are relevant for GDB
[GDB]
gdb_path = "../.platformio/packages/toolchain-gccarmnoneeabi/bin/arm-none-eabi-gdb"
instance = "stm32"

# tracing will ignore function names that match the following regex 
# see https://docs.python.org/3/library/re.html
ignore_functions_regex = "malloc|free|_strtod_l|__aeabi_dadd|__floatdidf|__floatundidf|strlen|memset"


# Type of watchpoint (e.g. (uint8_t*), (uint16_t*), (uint32_t*), (char*), etc.).
# Sometimes it can be a little bit tricky to find the correct type because
# (uint8_t*) == (char*) == (uint8*) but it is not everytime clear, which type will be accepted.
# You know you do it wrong if you get the ERROR message 'No symbol table is loaded.  Use the "file" command.' when
# setting a watchpoint
watchpoint_type = "(char*)"
# Number of available watchpoints (must be positive)
watchpoint_count = 4
# Time how long GDB should wait for responses from GDBServer in seconds
timeout = 30
entrypoint = "cJSON_Parse"
exitpoint = ""

input_buffer = "buf"
#0x200003a0


[LOGS]
# One of {DEBUG, INFO, WARNING, ERROR, CRITICAL}
log_level = "INFO"

[stm32]

gdb_server_path = "st-util -p 4243"
#Written in address:port
gdb_server_address = ":4243"

# Comparator Function register DWT_FUNCTIONn first address
dwt_function_reg = "0xe0001028"
