# Copyright (c) 2023 Robert Bosch GmbH
# SPDX-License-Identifier: AGPL-3.0

"""Thin process wrapper around NAUTILUS's generator binary."""

from __future__ import annotations

import os
import subprocess
import sys
import sysconfig
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Union


class NautilusError(RuntimeError):
    """Raised when the NAUTILUS generator cannot produce inputs."""


@dataclass(frozen=True)
class GeneratedInput:
    index: int
    data: bytes

    @property
    def preview(self) -> str:
        return self.data[:120].decode("utf-8", errors="replace")


def generate_inputs(
    grammar_path: Union[str, Path],
    nautilus_dir: Union[str, Path],
    *,
    tree_depth: int = 40,
    count: int = 1,
    cargo: str = "cargo",
    timeout_seconds: int = 180,
) -> tuple[GeneratedInput, ...]:
    """Generate inputs with NAUTILUS and return the generated bytes."""

    if count < 1:
        return ()

    grammar_path = Path(grammar_path).resolve()
    nautilus_dir = Path(nautilus_dir).resolve()
    manifest_path = nautilus_dir / "Cargo.toml"
    if not manifest_path.is_file():
        raise NautilusError(f"NAUTILUS Cargo.toml not found at {manifest_path}")

    with tempfile.TemporaryDirectory(prefix="gdbminer-nautilus-") as tmp_dir:
        tmp_path = Path(tmp_dir)
        command = [
            cargo,
            "run",
            "--quiet",
            "--manifest-path",
            str(manifest_path),
            "--bin",
            "generator",
            "--",
            "-g",
            str(grammar_path),
            "-t",
            str(tree_depth),
            "-n",
            str(count),
            "-s",
        ]
        completed = subprocess.run(
            command,
            cwd=tmp_path,
            check=False,
            capture_output=True,
            env=_nautilus_env(),
            timeout=timeout_seconds,
        )
        if completed.returncode != 0:
            raise NautilusError(
                "NAUTILUS generator failed with exit code "
                f"{completed.returncode}\n"
                f"stdout:\n{completed.stdout.decode(errors='replace')}\n"
                f"stderr:\n{completed.stderr.decode(errors='replace')}"
            )

        corpus_path = tmp_path / "corpus"
        generated: list[GeneratedInput] = []
        for corpus_file in sorted(
            corpus_path.iterdir(), key=lambda path: int(path.name)
        ):
            generated.append(
                GeneratedInput(
                    index=int(corpus_file.name), data=corpus_file.read_bytes()
                )
            )
        return tuple(generated)


def _nautilus_env() -> dict[str, str]:
    env = os.environ.copy()
    env["PYO3_PYTHON"] = sys.executable

    python_libdir = sysconfig.get_config_var("LIBDIR")
    if python_libdir:
        existing_library_path = env.get("LD_LIBRARY_PATH")
        env["LD_LIBRARY_PATH"] = (
            f"{python_libdir}:{existing_library_path}"
            if existing_library_path
            else python_libdir
        )

    return env
